[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#static"
  port = 8888

[[redirects]]
  from = "/v1/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

[[redirects]]
  from = "/v1/github/connections"
  to = "/.netlify/functions/github-connections-create"
  status = 200
  force = true

[[redirects]]
  from = "/v1/github/connections/me"
  to = "/.netlify/functions/github-connections-me"
  status = 200
  force = true

[[redirects]]
  from = "/v1/github/callback"
  to = "/.netlify/functions/github-callback"
  status = 200
  force = true

 [[redirects]]
   from = "/v1/github/webhooks"
   to = "/.netlify/functions/github-webhooks"
   status = 200
   force = true